### ISSUE TITLE
avahi-discover: UnicodeDecodeError with fr_BE.UTF-8 locales

### ISSUE THREAD

**Issue by bigon** [lathiat/avahi#158]
Hi,

With fr_BE.UTF-8 locales I get the following traceback when clicking on the devices in avahi-discover:

```Service data for service 'HP LaserJet P2055dn [447A47]' of type '_http._tcp' in domain 'local' on 3.0:
	Host NPI447A47.local (192.168.1.52), port 80, TXT data: []
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/bin/avahi-discover", line 113, in service_resolved
    self.update_label(interface, protocol, name, stype, domain, host, aprotocol, address, port, avahi.txt_array_to_string_array(txt))
  File "/usr/bin/avahi-discover", line 246, in update_label
    infos = infos % (stype, name, domain, self.siocgifname(interface), self.protoname(protocol), host, address, port, txts.strip())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20: ordinal not in range(128)```
 
Switching to LC_ALL=C fixes the issue

Avahi: 0.7

**Comment by gatuno1** [comment]
A workaround for this problem is calling avahi-discover changing LANGUAGE to english:
$ LANGUAGE="en_US.UTF-8" avahi-discover
