### ISSUE TITLE
fuzz test runtime error: left shift of 186 by 24 places cannot be represented in type 'int' in dns.c

### ISSUE THREAD

**Issue by traffic-millions** [lathiat/avahi#267]
the fuzz test err are as follows:
```
#3774   NEW    cov: 68 ft: 83 corp: 17/246b lim: 21 exec/s: 0 rss: 23Mb L: 17/21 MS: 1 ChangeBit-
dns.c:458:20: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
    #0 0x4b5b39 in avahi_dns_packet_consume_uint32 /src/avahi/avahi-core/dns.c:458:20
    #1 0x4b60e9 in avahi_dns_packet_consume_record /src/avahi/avahi-core/dns.c:634:9
    #2 0x4b3ea7 in LLVMFuzzerTestOneInput /src/avahi_packet_consume_record_fuzzer.cc:24:24
    #3 0x443081 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #4 0x4427a5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:470:3
    #5 0x444b47 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:698:19
    #6 0x4458d5 in fuzzer::Fuzzer::Loop(std::Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:830:5
    #7 0x433a58 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:824:6
    #8 0x45dad2 in main /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #9 0x7f11c0bf382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x407058 in _start (/out/avahi_packet_consume_record_fuzzer+0x407058)
```

**Comment by traffic-millions** [comment]
@lathiat
