### ISSUE TITLE
avahi daemon crashes 

### ISSUE THREAD

**Issue by techonline** [lathiat/avahi#278]
Hi,
I am using avahi version 0.8
After boot up while avahi-daemon is running if I run my app there isnt any problem.
But unicast doesnt work. I had to kill avahi-daemon and run again.
But after restarting avahi-daemon when I start my app, avahi daemon crashes. If I run my app first and then start avahi-daemon it doesnt crash.
Here is the core stack trace when I run my app with gdb.

Thread 16 "nmos-node" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 21429]
0x0000007fbf1e5210 in avahi_entry_group_free () from /usr/lib/libavahi-core.so.7
(gdb) bt
#0  0x0000007fbf1e5210 in avahi_entry_group_free () from /usr/lib/libavahi-core.so.7
#1  0x0000007fbf1b82e4 in avahi_client_free () from /usr/lib/libavahi-client.so.3
#2  0x0000007fbf23309c in ?? () from /usr/lib/libdns_sd.so.1
#3  0x0000007fbf234b88 in DNSServiceRegister () from /usr/lib/libdns_sd.so.1
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by techonline** [comment]
I have tracked it down. The app was setting a domain name as "testsuite.nmos.tv" which was causing the crash.I have now modified it to use default domain name. It works fine now.
